### ISSUE TITLE
The plugin knock out whole 2.4 installation.

### ISSUE THREAD

**Issue by ronlinet** [maxrossello/redmine_app_timesheets#44]
After having installed the plugin all pages return error : 
“Page not found The page you were trying to access doesn't exist or has been removed.”

Uninstalling the plugin brings the application back to live. 

The error logs:
App 17261 stderr:   lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
App 17261 stderr:   lib/redmine/menu_manager.rb:102:in `render_menu_node'
App 17261 stderr:   lib/redmine/menu_manager.rb:91:in `block in render_menu'
App 17261 stderr:   lib/redmine/menu_manager.rb:168:in `block in menu_items_for'
App 17261 stderr:   lib/redmine/menu_manager.rb:165:in `each'
App 17261 stderr:   lib/redmine/menu_manager.rb:165:in `menu_items_for'
App 17261 stderr:   lib/redmine/menu_manager.rb:90:in `render_menu'
App 17261 stderr:   app/views/layouts/base.html.erb:25:in `_app_views_layouts_base_html_erb___1458084633371167123_21855880'
App 17261 stderr:

**Comment by maxrossello** [comment]
My old 2.4 installation works as expected.
Make sure you followed all installation instructions, and that you have no other plugin which may be not compatible (try to execute timesheets in isolation first).

Time to upgrade to a more recent Redmine version, anyway. Redmine.org does not support 2.4 any more, as well as 2.5.

Regards,
  Massimo

**Comment by ronlinet** [comment]
Thank you for feedback. 
I will try upgrade the redmine release and see if it fixes the issue. 
Regards.
