### ISSUE TITLE
Redmine 3.0 Compatibility

### ISSUE THREAD

**Issue by greyman888** [maxrossello/redmine_app_timesheets#45]
Hi,

Our organisation would like to move to Redmine 3.0 and I was wondering if you have any plans to make your timesheet plugin compatible?

I've set up a Redmine 3.0 development environment (config at the bottom) and installed:

- redmine_app__space
- redmine_app_timesheets

Here are the results so far:

**app__space**

Appears to work without errors

**Orders**

- Allows you to create a global order but does not allow you to add users or groups. Clicking on the 'Add user' and 'Add group' does not do anything. I can provide more information on generated log entries.

- It is possible to create a local order using the custom field in the Version create view. After doing that creating a New Project gives the following error:

```
ActiveRecord::StatementInvalid in Projects#settings
PG::SyntaxError: ERROR:  subquery has too many columns
LINE 2: ...(versions.project_id != 2 AND versions.project_id IN (SELECT...
<snip>
```

**Timesheet**

- The timesheet view fails with the following error:

```
ArgumentError in TimesheetsController#index
    Support for calling #default_scope without a block is removed. For example instead of default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)
```

**Spent Time - Details Tab**

- Appears to work without errors

**Spent Time - Report Tab***
- Fails with the same error as above:
```
ArgumentError in Timelog#report
"Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)"
```

*Environment:*
Redmine version                3.0.0.devel
Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
Rails version                  4.2.0
Environment                    development
Database adapter               PostgreSQL

*SCM:*
Subversion                     1.8.8
Mercurial                      2.8.2
Cvs                            1.12.13
Bazaar                         2.7.0
Git                            1.9.1
Filesystem

*Redmine plugins:*
redmine_app__space             1.0.3
redmine_app_timesheets         1.4.12

**Comment by maxrossello** [comment]
Hi Adam,
unfortunately we are not shifting to Redmine 3.0 so soon, and currently I am still very busy after another project. I will get into it ASAP. 

You detailed test is very useful and will help a lot, thank you!

**Comment by greyman888** [comment]
I understand. When you do get into it, please let me know if there is a way
I can help.

**Comment by maxrossello** [comment]
Please find new branch 1.5-dev. It should be compatible with Redmine 3.0 and backward compatible as well.
As this branch turns to be considered stable, I will split a 1.4_stable branch from master and merge 1.5-dev to master.

Closing this issue as I expect new issues to be opened for each specific problem.
Thank you!

**Comment by greyman888** [comment]
Thank you. That was very fast! 

I will start some testing today.

**Comment by maxrossello** [comment]
Yeah, no rocket science there, so I found some time to accomplish :-)
