### ISSUE TITLE
Remove plugin v1.5

### ISSUE THREAD

**Issue by freeuser** [maxrossello/redmine_app_timesheets#52]
Hi there,
I have an issue during the uninstal process of the plugin:

cmd>> rake redmine:plugins:migrate NAME=redmine_app_timesheets VERSION=0 RAILS_ENV=production

-------------------------------------------------------------------------------------------------------------------------------
(in /var/www/redmine-3.0.1)
Migrating redmine_app_timesheets (Redmine Timesheets Application)...
== 12 VersionIsOrder: reverting ===============================================
-- remove_column(:versions, :is_order)
   -> 0.0982s
== 12 VersionIsOrder: reverted (0.3082s) ======================================

== 11 TsRemoveIssues: reverting ===============================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration/var/www/redmine-3.0.1/plugins/redmine_app_timesheets/db/migrate/011_ts_remove_issues.rb:11:in `down'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:827:in `down'
/var/lib/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/migration.rb:802:in `migrate'
/var/www/redmine-3.0.1/lib/redmine/plugin.rb:474:in `migrate_plugin'
/var/www/redmine-3.0.1/lib/redmine/plugin.rb:446:in `migrate'
/var/www/redmine-3.0.1/lib/redmine/plugin.rb:457:in `migrate'
/var/www/redmine-3.0.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
-------------------------------------------------------------------------------------------------------------------------------
Results: 500 internal error during redmine access

**Comment by maxrossello** [comment]
Just remove the exception in db/migrate/011_ts_remove_issues.rb line 11.

It is actually better removed now that there is no reason to downgrade to a previous version of the plugin, unless to uninstall it

**Comment by freeuser** [comment]
Perfect, now I've removed the plugin but 500 internal error remains: 

---------------------------------------------------------------------------------------------------------------------------------
Starting Application Space plugin for Redmine
Starting Timesheets Application
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:RichFile> at /var/lib/gems/1.9.1/bundler/gems/rich-99f662921998/app/models/rich/rich_file.rb:13)
Started GET "/" for xxx.xxx.xxx.xxx at 2015-05-27 16:00:31 +0000
Processing by WelcomeController#index as HTML
  Current user: mr.x (id=4)
  Rendered news/_news.html.erb (114.1ms)
  Rendered welcome/index.html.erb within layouts/base (410.3ms)
Completed 500 Internal Server Error in 857ms

ActionView::Template::Error (undefined method `split' for nil:NilClass):
    42:     <% end %>
    43:
    44:     <h1><%= page_header_title %></h1>
    45:
    46:     <% if display_main_menu?(@project) %>
    47:     <div id="main-menu">
    48:         <%= render_main_menu(@project) %>
  lib/redmine/menu_manager.rb:446:in `call'
  lib/redmine/menu_manager.rb:446:in `allowed?'
  lib/redmine/menu_manager.rb:164:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:163:in `each'
  lib/redmine/menu_manager.rb:163:in `menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  lib/redmine/menu_manager.rb:80:in `render_main_menu'
  app/views/layouts/base.html.erb:45:in `_app_views_layouts_base_html_erb___1795593666930682684_28000820'

**Comment by maxrossello** [comment]
Have you removed the plugin and restarted the server?

**Comment by freeuser** [comment]
I've
- Removed plugins, restarted redmine and 500 internal error
- Reinstalled plugins, unistalled, removed, restarted: now ok!
Tnx
