### ISSUE TITLE
redmine 3.0.x

### ISSUE THREAD

**Issue by Zonork** [maxrossello/redmine_app_timesheets#53]
i install redmine_app_timesheets afer install redmine_app__space and have no errors, but whe i try to use it redmine_app__space is not full working, i test the instalation in a redmine 2.5.2 and works, redmine_app__space show only compatible with redmine 2.3.2, 2.4.2, 2.5.1 compatible with 2.x and redmine_app_timesheets with Redmine 3.0.1, compatible with 2.x. 

redmine_app_timesheets is really working on redmine 3.0.x?

**Comment by maxrossello** [comment]
Yes, the app space plugin is being used on 3.0 without modifications, and the timesheet plugin has been ported.
Maybe you could explain what the error is?

**Comment by dzhgenti** [comment]
Hi,

We're also having issues with configuration. Trying to configure it on redmine 3.0.4. There are no any errors, but we can't figure out what needs to be done. Here is plugin config page: 
[!](http://screencast.com/t/v587FJgqOmgk)
In Timesheets project we enabled time tracking module. Tried to create versions with "is order" flag both in timesheets project and in individual projects. Tried to log time into issues added into order versions, but still can't find anything similar to screenshots on the plugin page.
Applications page from the main navigation
(http://screencast.com/t/khfrZQaFhrAj)
Applications space plugin configuration page:
[!](http://screencast.com/t/EAOCl5lZg)
Our guess is that something doesn't work with 3.0.4. But we haven't tried this plugin on 2.x so can't event understand if this is a bug or misconfiguration

**Comment by maxrossello** [comment]
problem seems with the app space plugin at first.
Have you run the rake migrations? what version of ruby and rails are you using?

**Comment by dzhgenti** [comment]
Well, seems like we've figured it out. False alarm :)

**Comment by maxrossello** [comment]
ok, thank you
