### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by danpilch** [maxrossello/redmine_app_timesheets#57]
I have just installed the redmine app timesheets plugin following the install instructions. I ahve enabled the plugin in Administration --> Applications --> Timesheet (everybody)

I then clicked onto Applications top left then Timesheet.

I am then presented with:

    Timesheet for Joe Bloggs

    Please configure the application here.

Upon clicking 'here' I receive a 404 error:

    Not Found

    The requested URL /settings/plugin/redmine_app_timesheets was not found on this server.

I can't see anything in the logs of interest.

Any help would be appreciated. 

Redmine 2.5.1
Ruby 1.9.3

**Comment by maxrossello** [comment]
Do you mean that you also followed the "General configuration" paragraph?
Can you see the plugin listed into /admin/plugins ?

**Comment by maxrossello** [comment]
Closed for being idle. Please reopen if the issue is still unresolved
