### ISSUE TITLE
Unable to set permission in Orders Setting

### ISSUE THREAD

**Issue by nqminhdlvn** [maxrossello/redmine_app_timesheets#68]
First of all, your plugin is quite good and it fixes to what my company needs.

I have a issue and really need your help since I have no experience in coding or programming.

Environment:
+ OS: CentOS7
+ Redmine version: 3.0.5
+ Rail version: 4.2.3
+ Plugin "Redmine Timesheet Application" version: 1.5.3

The issue is I'm unable to set permission in order settings as picture below

![order settings](https://cloud.githubusercontent.com/assets/15881129/11200211/9644028a-8d06-11e5-9aae-6b83f2599479.JPG)

These icons seem unable to click on and all turn to gray except "delete/trash" icon.

Can you assist me on this?

If you need any further information, please do let me know.

Thank you

**Comment by maxrossello** [comment]
Hi,
please have a look at https://github.com/maxrossello/redmine_app_timesheets#user-and-group-visibility
The users you list are either Redmine administrators or listed as Orders administrators, this is why the angel icon shows and other options are useless.
You may want to try to remove access to the Order administration application to some of that users and see what happens (do that in /settings/plugin/redmine_app__space).

**Comment by nqminhdlvn** [comment]
Hi maxrossello,
I think I know exactly what is my trouble :)
Thank you a lot for your explanation above.
