### ISSUE TITLE
Wiki page added

### ISSUE THREAD

**Issue by greyman888** [maxrossello/redmine_app_timesheets#74]
Hi Max,

I've finally added a page to the wiki as I promised. Sorry I took so long. 

This version is my second draft. My first attempt was so long and detailed it ended up just being confusing and boring.

My intention with this page was to not duplicate the information that you already have in the readme file so I tried to add a description on how to configure redmine/timesheet for very complex situations. Let me know if you think it is OK.

Adam

**Comment by maxrossello** [comment]
Thank you so much, I'll have a look

**Comment by maxrossello** [comment]
I added some comments to your page. It was great, I just added some comments to make it more general. Thank you!
