### ISSUE TITLE
activity_id and order_activity_id

### ISSUE THREAD

**Issue by fafnir1990** [maxrossello/redmine_app_timesheets#86]
Hello
I would like to ask, why there are two columns (activity_id and order_activity_id) in time_entries table?
I`ve found one malfunction (in my opinion). The problem is when:

1. New row is added via "Timesheet", clicked save, added hours and clicked save.
2. Order Activity is changed, clicked save

In database Order_activity_id is new, but activity_id remains old.
Users observed difference between "Details" and "Report" values in "Spent time" due to inconsistency described above (Details uses "activity_id", Report uses "order_activity_id")
 
I`ve used temporarily solution (trigger which update activity_id by order_activity_id).

Thanks in advance for reply
Best regards 
Rafał

**Comment by maxrossello** [comment]
Hi,
the same logic that makes Orders different from Versions, also make Order Activities different from Activities.
Order Activities can be enabled/disabled and used independently from Activities, and you can split the Spent time reports both per Activities and Order Activities (even simultaneously). Tracking time for project purposes is different from tracking time for financial administration, albeit they might coincide sometimes.

**Comment by fafnir1990** [comment]
Ok. Thank you very much for reply!
Best regards

**Comment by maxrossello** [comment]
You're welcome
