### ISSUE TITLE
Redmine 4.1.x.x?

### ISSUE THREAD

**Issue by konpega** [maxrossello/redmine_app_timesheets#88]
May anybody could help for the new versions of Redmine especially for 4.1.0.8 ? 
Thanks in advance

**Comment by maxrossello** [comment]
I'd love to regain support of this plugin into the https://github.com/maxrossello/redmine_testsuites suite someday, but anyways it would happen on the latest Redmine supported version, which today is 5.1.x.

Thanks for your interest

**Comment by konpega** [comment]
I will try also and inform if it works, I could not change all others unfortunately. Anyhow thanks for your effort and reply.
